### ISSUE TITLE
🔥 [🐛] RNGoogleMobileAdsExample Status bar could not be hidden for full screen ad

### ISSUE THREAD

**Issue by puckey** [invertase/react-native-google-mobile-ads#136]
## Issue

When I display an Interstitial in the iOS RNGoogleMobileAdsExample example app on my phone (iPhone SE), I see the following warning in the output:

> 2022-05-09 14:32:51.757814+0200 RNGoogleMobileAdsExample[480:45469] <Google> Status bar could not be hidden for full screen ad. Ensure that your app is configured to allow full screen ads to control the status bar. For example, consider whether you need to set the childViewControllerForStatusBarHidden property on your ad's rootViewController.

In the past I have had issues where users were unable to close interstitials due to the close button being under the status bar. Might this be related to this warning?

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Sorry for being silent on this one until now - I appreciate the report and it appears it needs triage

**Comment by parasdaryanani** [comment]
I'm seeing this warning in the console as well. Until there's a more permanent fix I'm using a workaround by toggling the status bar as follows:

```javascript
import { StatusBar } from 'react-native';

...

const MyScreen = () => {

  const { isLoaded, isClosed, isEarnedReward, reward, load, show } =
    useRewardedAd(adUnitId, {
      requestNonPersonalizedAdsOnly: true,
      keywords: ["fashion", "clothing"],
    });

  useEffect(() => {
    if (isClosed) {
      StatusBar.setHidden(false);
      navigation.navigate("CompletionScreen");
    }
  }, [isClosed, navigation]);

  const handleShowAd = () => {
    StatusBar.setHidden(true);
    show();
  };

};
```

**Comment by bitfabrikken** [comment]
@mikehardy 
This is a quite serious bug - if a specific interstitial is shown on some devices, the app is useless because the user cannot close the ad.

Been seeing this too - but not the warning since it's happening on a live app.
People have been complaining they can't close the interstitial ad on some devices.

Today I tested on 30+ devices on stackoverflow, and it only happened in these cases:
- iPhone SE 2022 (iOS 15), iPhone 8 (iOS 15.3).
- A specific type of interstitial ad which requires two clicks to close. I got them for Candy Crush, Shoot Bubble, Cubes Empire.

I could close the ad by clicking pixel-perfectly on the absolute bottom of the button, indicating something is blocking the clicks. There's only maybe 1-4 pixels in the height which reacts to the click.

Of course this wonderful issue doesn't occur in Simulators, as these can't seem to show non-test ads, which don't have this particular type of interstitial.
And they also only happen for very few specific devices, and on top of that, only for some specific ads - which for some only happen a couple times a day.

Other devices this did NOT appear on - i.e. no issues:
- iPhone 13 Mini (15)
- iPhone 13 (15)
- iPhone 13 Pro (15.6)
- iPhone 13 Pro (15.0)
- iPhone 13 Pro Max (15.0)
- iPhone 13 (15.5)
- iPhone 13 (15.4)
- iPhone 12 (14)
- iPhone 12 Mini (16 beta)
- iPhone 12 Mini (14)
- iPhone 12 Pro Max (16 beta)
- iPhone 12 Pro Max (14)
- iPhone 12 Pro (14.4)
- iPhone XS (15.3)
- iPhone XS Max (12)
- iPhone 11 Pro (15.4)
- iPhone 11 Pro Max (14.0)
- iPhone XR (15.0)
- iPhone 8 (12)
- iPhone 7 (12.3)
- iPhone 6S (12.1)
- iPhone 8 Plus (12.3)
- iPad Air 5 (15)
- iPad Air 4 (14)
- iPad Mini 2021 (15)
- iPad Pro 2021 (12.9)
- iPad Pro 12.9 2018 (15.3)
- iPad Pro 11 2021 (14.5)
- iPad 5th (15.3)

**Comment by mikehardy** [comment]
needs triage for anyone whose business is affected...
