### ISSUE TITLE
[📚] How to implement California Consumer Privacy Act (CCPA)

### ISSUE THREAD

**Issue by RodolfoGS** [invertase/react-native-google-mobile-ads#172]
## How to implement California Consumer Privacy Act (CCPA)

I didn't found any reference in the documentation nor in another issues related to how to implement the "Do Not Sell My Personal Information" option for California users.

I only found the "European User Consent", not the CCPA of California.
https://docs.page/invertase/react-native-google-mobile-ads/european-user-consent

Anyone know what I need to do to implement this?

Docs:
AdMob: https://support.google.com/admob/answer/9561022?hl=en
iOS SDK: https://developers.google.com/admob/ios/ccpa
Android SDK: https://developers.google.com/admob/android/ccpa

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hey @RodolfoGS - this does not appear to be implemented. If this is a use case your business needs, we'd welcome a PR here supporting it.

It does appear based on my reading that our integration of the UMP (User Messaging Platform - #82) allows you to obtain consent or not for personalized ads, and that personalized ads vs non-personalized ads are the difference for CCPA "do not sell my data" data processing.

It does appear based on my reading of your links that compliance with the CCPA for users that do not consent is also fulfilled by serving non-personalized ads, and there are a variety of ways to do that.

This seems to have all the things you need for gathering consent https://docs.page/invertase/react-native-google-mobile-ads/european-user-consent#inspecting-consent-choices

This seems to be the flag you need that would comply with a non-consenting CCPA user? https://github.com/invertase/react-native-google-mobile-ads/blob/5d2048b530b798740c9fed392772568f909dd6b2/src/types/RequestOptions.ts#L25

So while it appears that there are/were some CCPA specific items prior, I think google has moved on with the UMP as a more generic way of handling consent across all of these different regulatory environments, and with more generic ad request options in order to handle the different kinds of consent. And they are better than the CCPA-specific items above

It may be that with these items you have everything you need? It seems that way to me.

**Comment by RodolfoGS** [comment]
Thanks @mikehardy, I'll use the `requestNonPersonalizedAdsOnly` flag 👍
