### ISSUE TITLE
[🐛] How can use custom events?

### ISSUE THREAD

**Issue by ManhVuAmela** [invertase/react-native-google-mobile-ads#223]
## Issue

How can I use this library with the custom events: https://developers.google.com/admob/ios/custom-events/rewarded

Like https://developers.geniee.co.jp/en/ios/setup/, when I pod install like docs, google-mobile-ads can't recognize that SDK

Thanks

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!

> when I pod install like docs, google-mobile-ads can't recognize that SDK

Reports of problems should always be accompanied with exact steps to reproduce, and error messages. Without them it is not actionable.

https://stackoverflow.com/help/how-to-ask

In order to get custom events you will apparently need to write native code that implements the adapter interface, as indicated in the docs. That's not something I think we may support here in general  - the easiest thing to do might be to fork the library and maintain a patch on it, or *if* there is a way to implement the extensions in a generic way, perhaps as a PR - but it's not something the library supports at the moment, sorry
