### ISSUE TITLE
Not working with RN 0.59.10 ?

### ISSUE THREAD

**Issue by Kupascafe** [invertase/react-native-google-mobile-ads#229]
I am using RN 0.59.10 with android emulator
using npm it installed version `^8.1.0`
then I did `react-native link react-native-google-mobile-ads`
I got some errors when building my app
```
* What went wrong:
A problem occurred evaluating project ':react-native-google-mobile-ads'.
> Failed to apply plugin [id 'kotlin-android']
   > The current Gradle version 5.4.1 is not compatible with the Kotlin Gradle plugin. Please use Gradle 6.1.1 or newer, or the previous version of the Kotlin plugin.
```
and

```
* What went wrong:
A problem occurred configuring project ':react-native-google-mobile-ads'.
> compileSdkVersion is not specified.
```
any idea how to resolve this?
Which version of `react-native-google-mobile-ads` should i use with RN 0.59.10?

**Comment by mikehardy** [comment]
With apologies, there is no expectation whatsoever here, or in the general react-native community, that react-native < 0.60 will work. This repository did not even exist until react-native 0.67 was released I think

For this repository specifically I think you will want >= 0.64 due to event emitter changes in react-native

It's important to note that Xcode 13 is required by Apple for new uploads starting in just a couple weeks, and react-native does not even compile correctly with Xcode 13 until react-native 0.65 so I don't see any valid reason to stay on such an old version.

I understand upgrading may have been difficult in the past, but in modern times, this website helps a lot if you go version by version just applying the changes one version at a time: https://react-native-community.github.io/upgrade-helper/
