### ISSUE TITLE
Does the library work in Russia?

### ISSUE THREAD

**Issue by valery-lavrik** [invertase/react-native-google-mobile-ads#231]
I've been trying to launch it for half a day, I keep getting an error

![2022-09-26_16-54-20](https://user-images.githubusercontent.com/8047999/192296475-fc734173-eaea-4258-bd1e-104153cbbf0d.png)

The error occurs here

![2022-09-26_16-54-39](https://user-images.githubusercontent.com/8047999/192296558-bf796dc5-e33b-4e77-a6bf-eb1b41efc0ce.png)

The settings in the admob panel are exactly correct.

Maybe the problem is in my country (Russia)?

**Comment by mikehardy** [comment]
> Maybe the problem is in my country (Russia)?

Maybe?

no-fill is not in this library's control, it's an underlying issue so you should be searching for information in a more generic way "admob nofill" or "admob nofill russia". We have a small guide about them since it's a frequent topic but there is not a lot we can do 

https://docs.page/invertase/react-native-google-mobile-ads/common-reasons-for-ads-not-showing

With apologies, I do not think this is actionable here beyond sharing our documentation so I will close
