### ISSUE TITLE
Is support lite version?

### ISSUE THREAD

**Issue by merbin2012** [invertase/react-native-google-mobile-ads#265]
### Documentation Feedback

How can I use the Admob lite version?

**Comment by mikehardy** [comment]
Hi there, we do not currently support the lite version.
It appears you may just alter this line in build.gradle to reference the lite SDK dependency instead of the current one though:

https://github.com/invertase/react-native-google-mobile-ads/blob/95d53cb9c79275c92b69e61d95cacef85aa434d9/android/build.gradle#L120

The versions appear to be identical:

https://github.com/invertase/react-native-google-mobile-ads/blob/95d53cb9c79275c92b69e61d95cacef85aa434d9/package.json#L52
https://developers.google.com/admob/android/lite-sdk

Open source means "try it and see", patch-package is your friend (https://github.com/ds300/patch-package) if it works, you can propose a PR that adds a toggle in app.json config block allowing library users to switch which one they want to use?

**Comment by merbin2012** [comment]
@mikehardy Thank you very much.
