### ISSUE TITLE
[🐛] Error making request.

### ISSUE THREAD

**Issue by huseyintamer** [invertase/react-native-google-mobile-ads#281]
### What happened?

**I found a bug in Sentry that hundreds of my users are experiencing.**

The error occurs at the end of this function.

  `  const consentInfo = await AdsConsent.requestInfoUpdate();`

Error message: `Error making request.`

It happens on Android 9,10,11,12.

Phone models of some of the users who got the error. : A063, V2205, V2149, moto g(10) power, RMX3286, RMX1827

Looking forward to your help, thanks.

**full code**

```
  const requestPermissionEu = async () => {
    console.log('func:requestPermissionEu');
    try {
      const request = await fetchPermissionStatus();
      const consentInfo = await AdsConsent.requestInfoUpdate();
      if (
        consentInfo.isConsentFormAvailable &&
        consentInfo.status === AdsConsentStatus.REQUIRED &&
        request
      ) {
        const {status} = await AdsConsent.showForm();
        writePermissionStatus();
      }
    } catch (error) {
      Sentry.captureException(error);
    }
  };
```

**Example User Permission Status**

`{
ACCESS_NETWORK_STATE: granted,
ACCESS_NOTIFICATION_POLICY: granted,
ACCESS_WIFI_STATE: granted,
AD_ID: granted, autofocus: not_granted,
BILLING: granted,
BIND_GET_INSTALL_REFERRER_SERVICE: granted,
BROADCAST_CLOSE_SYSTEM_DIALOGS: not_granted,
CAMERA: granted,
CHECK_LICENSE: granted,
FOREGROUND_SERVICE: granted,
INTERNET: granted, 
POST_NOTIFICATIONS: not_granted,
READ_EXTERNAL_STORAGE: granted,
RECEIVE: granted,
RECEIVE_BOOT_COMPLETED: granted,
RECORD_AUDIO: not_granted,
SCHEDULE_EXACT_ALARM: not_granted,
SYSTEM_ALERT_WINDOW: not_granted,
USE_FULL_SCREEN_INTENT: granted,
VIBRATE: granted, WAKE_LOCK: granted,
WRITE_EXTERNAL_STORAGE: granted
}`

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) x64 Apple M1
    Memory: 23.10 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 2022.11.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0
    react-native-macos: Not Found
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```json
{
  "name": "hiface",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@gorhom/bottom-sheet": "^4.2.2",
    "@notifee/react-native": "^7.1.0",
    "@react-native-async-storage/async-storage": "^1.15.5",
    "@react-native-clipboard/clipboard": "^1.10.0",
    "@react-native-community/netinfo": "^7.1.5",
    "@react-native-firebase/analytics": "^16.4.3",
    "@react-native-firebase/app": "^16.4.3",
    "@react-native-firebase/auth": "^16.4.3",
    "@react-native-firebase/firestore": "^16.4.3",
    "@react-native-firebase/messaging": "^16.4.3",
    "@react-native-firebase/perf": "^16.4.3",
    "@react-native-firebase/remote-config": "^16.4.3",
    "@react-native-firebase/storage": "^16.4.3",
    "@react-native-masked-view/masked-view": "^0.2.8",
    "@react-native-picker/picker": "^2.2.1",
    "@react-navigation/bottom-tabs": "^5.9.2",
    "@react-navigation/drawer": "^5.10.1",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "@sentry/react-native": "^4.9.0",
    "axios": "^0.27.2",
    "i18n-js": "^3.9.2",
    "lottie-react-native": "^5.1.4",
    "moment": "^2.29.4",
    "react": "18.1.0",
    "react-content-loader": "^6.2.0",
    "react-native": "0.70.0",
    "react-native-adapty": "^1.2.1",
    "react-native-bootsplash": "^4.3.3",
    "react-native-camera": "^4.2.1",
    "react-native-compressor": "^1.6.1",
    "react-native-device-info": "^8.4.8",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-google-mobile-ads": "^8.2.1",
    "react-native-image-crop-picker": "^0.35.1",
    "react-native-in-app-review": "^3.2.3",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-localize": "^2.1.5",
    "react-native-paper": "4.12.5",
    "react-native-permissions": "^3.3.1",
    "react-native-reanimated": "^2.13.0",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.15.0",
    "react-native-share": "^7.3.9",
    "react-native-svg": "12.1.0",
    "react-native-swiper": "^1.6.0",
    "react-native-system-navigation-bar": "^2.0.0",
    "react-native-tenjin": "^1.0.2",
    "react-native-vector-icons": "^9.1.0",
    "react-native-webview": "^11.23.1",
    "rn-fetch-blob": "^0.11.2",
    "use-interval": "^1.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.72.1",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

### app.json

```json
{
  "name": "Hiface",
  "displayName": "Hiface",
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-********~********",
    "delay_app_measurement_init": true
  },
  "plugins": ["react-native-compressor"]
}
```

**Comment by mikehardy** [comment]
Okay, so options is empty as a parameter of that code sample, meaning you drop immediately to here:

https://github.com/invertase/react-native-google-mobile-ads/blob/b04ad7cc5e78116e13252e8fba192fbb97b7e43b/src/AdsConsent.ts#L76

And you mention android so that goes here:

https://github.com/invertase/react-native-google-mobile-ads/blob/b04ad7cc5e78116e13252e8fba192fbb97b7e43b/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java#L60

Something in there is failing. You indicate you receive reports in sentry, but you do not indicate local reproduction. Can you reproduce this? Until you can, it will be difficult to fix so I'll consider that task 1. Once you can, I'm curious what `adb logcat` during the failure looks like?

It would be interesting to throw some `e.printStackTrace(System.err)` in there before the calls to `rejectPromiseWithCodeAndMessage` as well, to see what the raw stack was. Is it from params building, or from our code here having some parsing error and popping out to the higher-scope catch?

https://github.com/invertase/react-native-google-mobile-ads/blob/b04ad7cc5e78116e13252e8fba192fbb97b7e43b/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java#L98-L103

Or is it from the SDK here?

https://github.com/invertase/react-native-google-mobile-ads/blob/b04ad7cc5e78116e13252e8fba192fbb97b7e43b/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsConsentModule.java#L105-L107


You have not indicated any research conducted on your own prior to logging the issue?

https://search.brave.com/search?q=consentInformation.requestConsentInfoUpdate+%27Error+making+request%27

https://stackoverflow.com/questions/71597634/android-ump-request-consent-always-fails

There are several items there which have bearing on the problem. Do you assert they are all in order?

To set expectations on how the solution will be found here: I can guide you by pointing out interesting areas of the code, possibly useful knowledge from around the net but you will have to conduct the investigation fully and the solution will in the end come from the results of experiments during your investigation and/or any PRs you create that seem necessary. The configuration / setup of admob accounts etc is not something that is share-able or reproducible easily so there is no other path forward really. I do hope the pointers here set you quickly on the path though and I will merge any reasonable PRs (even if they are just to add better logging for diagnostics now + in the future...)

**Comment by huseyintamer** [comment]
Thanks for detailed explanation.

I  test it but I didn't experience the error. Because it's happen some devices.

it's detail sentry log: https://sentry.io/share/issue/cd9bc916a5ef48a08961a04c31879677/

I am not using requestPermissionEu function for now. So I got rid of the error. I will use it again if there is a problem in admob.

Best
