### ISSUE TITLE
Personalized Ad Consent SDK deprecated in favor of the User Messaging Platform SDK

### ISSUE THREAD

**Issue by dylancom** [invertase/react-native-google-mobile-ads#38]
The Personalized Ad Consent SDK is no longer being maintained. It has been deprecated in favor of the User Messaging Platform SDK , which is IAB compliant.

See: https://developers.google.com/admob/ump/ios/quick-start

**Comment by mikehardy** [comment]
oh my - take one year off from underlying SDK upgrades and it's a big treadmill to get back on track, especially in the fast-moving privacy API area...

**Comment by hannojg** [comment]
There already seems to be an RN library that uses this: https://github.com/birgernass/react-native-ad-consent

Maybe we can use that library in this one? For our app setup, I will use the named library for consent and this library for serving the ads. Another possibility might be to completely remove the AdsConsent module from this lib and use the named library for consent.

**Comment by birdofpreyru** [comment]
> Another possibility might be to completely remove the AdsConsent module from this lib and use the named library for consent.

This would be a bad choice. IMHO, a well-designed RN AdMob library should encapsulate everything ads-related, and provide a developer with all-covering instructions how to setup ads from zero to hero (including also asking for necessary permissions, which I am not sure, but I have a feeling that some should be requested separetely now). Otherwise, if a developer is supposed to go and learn himself all nuances of web-serving to different regions, on different platforms, and then assemble it with several separate libs... that kind of nullifies the overall purpose of RN.

**Comment by mikehardy** [comment]
Maybe @birgernass from the ad-consent library would like to collaborate / join us here ? We (Invertase) have a commitment to long-term maintenance and are a good home for code, but we do really need interested helpers. This library could be unified home for the whole thing

**Comment by birgernass** [comment]
This sounds like a good idea, and I'm happy to help. I have been following your work for quite some time and have no doubt that this library would make a good, unified home. I'm currently on vacation until next week though.

**Comment by tarouboy** [comment]
Is it mandatory to use the UMP as consent form or I can create my own one?

**Comment by hannojg** [comment]
@tarouboy deom what I understand you can totally use your own consent form.

**Comment by mikehardy** [comment]
@birgernass hey :wave: enjoy the vacation! Thanks for responding just to say it seems like it could work either way :-), we can think on how to move forward then until everyone is back at it in 2022. Cheers

**Comment by birgernass** [comment]
Hey everyone! Has there been any further discussion on how to move forward, e.g. do you want to keep the SDKs separated or do we want to integrate the UMP SDK into this project? If so, should I create a pull request and open a discussion there, or how would we proceed?

**Comment by dylancom** [comment]
To me it would be best if we integrate it within this lib and replace the already included "Personalized Ad Consent SDK". So would be great if you like to submit a PR.

**Comment by mikehardy** [comment]
I agree, when I researched it last it seemed that so long as we weren't angering committed people (that is: making someone who maintains a lib doing the same thing feel like we were not collaborative), that having it all in one spot was probably best. And since @birgernass - you seem to like the idea and I haven't had a change of thought, I think having it here would be great
