### ISSUE TITLE
[📚] How to reasume `delay_app_measurement_init`

### ISSUE THREAD

**Issue by Bartozzz** [invertase/react-native-google-mobile-ads#488]
### Documentation Feedback

As per documentation:

> By default, the Google Mobile Ads SDK initializes app measurement and begins sending user-level event data to Google immediately when the app starts. If your app will be used by users within the EEA, **it is important you prevent app measurement** until your first ad has been requested (after consent).

It is clear how to prevent app measurement via the `delay_app_measurement_init` flag, but how can I enable app measurement once the consent is given?

I implemented the consent form in my applications and it seems to be working just fine, but the analytics are not working correctly and data for the latest version (1.27.1) is not collected at all!

## Google Analytics

<img width="514" alt="image" src="https://github.com/invertase/react-native-google-mobile-ads/assets/6741707/95f8574b-61f3-45e0-b235-373751cc6d6c">

<img width="554" alt="image" src="https://github.com/invertase/react-native-google-mobile-ads/assets/6741707/8ead018e-7287-43f3-b261-81d910f71f80">

## Google Play

<img width="1648" alt="image" src="https://github.com/invertase/react-native-google-mobile-ads/assets/6741707/a7d08d70-9413-49c7-b0cc-31fe4136871e">

**Comment by mikehardy** [comment]
Without code posted I can't be sure, but after a quick spin through the documentation and some relevant posts on the support mailing list of admob, I think you have to call initialize for admob *after* obtaining consent. Are you initializing first, then obtaining consent, and not initializing after?

**Comment by Bartozzz** [comment]
I am first asking for consent, then initializing, as follows:

```ts
useEffect(() => {
  (async function initialize() {
    try {
      await AdsConsent.requestInfoUpdate({ testDeviceIdentifiers });
      await AdsConsent.loadAndShowConsentFormIfRequired();
    } catch (error) { /* ... */ }

    try {
      await mobileAds().setRequestConfiguration({ testDeviceIdentifiers, /* ... */ });
      await mobileAds().initialize();
    } catch (error) { /* ... */ }
  })();
}, [])
```

**Comment by mikehardy** [comment]
Then I must admit, I do not know, I am sorry. I was unable to find any API that we can use to directly start measurement - I looked at the reference documentation and even saw a post on the list that indicated one might exist but I was unable to locate it.

In the react-native-firebase context where I'm more consistently involved, when you toggle off the analytics via AndroidManifest or iOS plist (which we accomplish in that repo via firebase.json then some build-time scripting to make it more "react-native" style vs native - but it's the same end result) then there are native SDK APIs you call later to initiate things, and we've wrapped and exposed them such as https://rnfirebase.io/reference/analytics#setAnalyticsCollectionEnabled

I even looked at their samples ([here's the Banner one for example](https://github.com/googleads/googleads-mobile-android-examples/tree/main/java/admob/BannerExample/app/src/main/java/com/google/android/gms/example/bannerexample)) and I sadly did not see them attempting to delay measurement then re-enable it so I don't know

I was really expecting to find that here and simply did not. Perhaps I missed something? Have you scoured the reference docs and seen something I've missed?

It might be best to follow this process to move it forward, as I'm at the end of both things-I-know and time-I-have to investigate further:

- see if I missed anything in the APIs where there is an API we should wrap and expose here. That'd be easy

Otherwise:
- get the sample I link above, and build it run it (it hopefully just works out of the box)
- get some network monitoring set up (should be possible to set up on your host to monitor the emulator's network behavior) and monitor for connections to google's app measurement hosts (I believe they are well known if you search)
- with that you should be able to prove that as you open the app you start measurement? That's our baseline
- now alter the AndroidManifest to delay measurement and make sure it calls initialize after gathering consent
- see what the network monitor tells you

Post your fork of their samples with nothing but the commit to the AndroidManifest and your network findings to the google admob support mailing list and see what they say ?

May also be worthwhile to duplicate the post to stackoverflow to access broader community

**Comment by Bartozzz** [comment]
Unfortunately, I am no longer maintaining those applications and won't have time to debug this issue further. I am just updating them so they comply with the new requirements.

Do you think using `react-native-firebase` and triggering `setAnalyticsCollectionEnabled` once consent is given can be a viable work-around?

**Comment by mikehardy** [comment]
@Bartozzz with apologies I'm just not sure, that sounds like a *possible* path forward...it may work ? I'd ask on the admob google group and maybe run the experiment you outline above to see
