### ISSUE TITLE
Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown.

### ISSUE THREAD

**Issue by Ambreen-Kanwal20** [invertase/react-native-google-mobile-ads#492]
### What happened?

I'm using
"react-native-google-mobile-ads": "8.2.2".

All the banner and interstitial ads are working fine. I want to display rewarded ads in my application. I also updated the library to latest version : "react-native-google-mobile-ads": "12.4.0". But it gives me the same error.

<img width="747" alt="Screenshot 2023-11-29 at 10 55 05 AM" src="https://github.com/invertase/react-native-google-mobile-ads/assets/97061888/b976a82e-e13c-4ef4-8517-7c6c0194211f">

Kindly help me to fix this issue.

### Platforms

Android and iOS

### React Native Info

```Shell
"react-native": "0.69.5",
Xcode Version is : 13.2.1
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
"react-native": "0.69.5",
"react-native-google-mobile-ads": "8.2.2"
```

**Comment by mikehardy** [comment]
```
"react-native": "0.69.5",
Xcode Version is : 13.2.1

```

These are old versions, and while they may not be your problem, it is always suspect to ask for help without using current versions of software. It makes reproductions unworkable because reproducing issues using same (older...) versions is a waste of time typically, and reproductions are critical. So that's a -1 for this report - you should update and make sure it still happens to make sure you aren't requesting time from maintainers for already-fixed issues

With regard to rewarded ads not loading, have you tried the sample app? If it works and loads the rewarded ad then there is something wrong in your app. It might be that the ad takes a while to load and you are attempting to show it too early.

We can reopen if the sample app has the same problem showing the ad *after it has loaded*
