### ISSUE TITLE
kotlin 1.9.X this libary does not work

### ISSUE THREAD

**Issue by jihokim2** [invertase/react-native-google-mobile-ads#493]
### What happened?

In Kotlin 1.8.X this library is working. But in Kotlin 1.9.X this is not. Please help us.

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```Shell
-
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
-
```

### app.json

```JSON
-
```

### android/build.gradle

```Groovy
buildscript {
    ext {
        buildToolsVersion = "33.0.2"
        minSdkVersion = 29
        compileSdkVersion = 33
        targetSdkVersion = 33
        googlePlayServicesAuthVersion = "20.7.0"
        kotlin_version = "1.9.21"
        kotlinVersion = "$kotlin_version" //react-native-brownfield
        supportLibVersion = "28.0.0"
        androidXAnnotation = "1.1.0"
        androidXBrowser = "1.0.0"
        playServicesVersion="18.2.0"
        playBillingSdkVersion="6.0.1"
        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.4.2")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:4.1.2")
        classpath 'com.google.gms:google-services:4.3.15'
        classpath "com.google.firebase.crashlytics:com.google.firebase.crashlytics.gradle.plugin:2.9.9"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
}
```

**Comment by mikehardy** [comment]
1- The error message you receive is...
2- You have a repository that we can work with easily that reproduces the problem and the link is...
3- You believe kotlin 1.9.21 should work because you've done it with a plain react-native example app initialized from scratch, we can see it in your reproduction repository if we check it out with this commit....

https://stackoverflow.com/help/how-to-ask

In my experience, kotlin 1.9.21 is problematic because they begin enforcing compatibility constraints, and a lot of modules aren't compatible. I don't think the answer to item 3 above is positive - I don't think react-native works well with kotlin 1.9.21 at all now and I challenge you to show it does. Maybe I'm wrong - I would love to see it, and proving it is just a `npx react-native init KotlinExample` away, then publish it to a repo where we can clone it

It appears that it may be possible to use arbitrary kotlin versions in react-native and this app may not support it, but it would get you closer to your goal.

Perhaps you need to propose a PR that alters the build.gradle to look for ext.kotlinVersion and use it if found? 

But it looks like we are already doing that: https://github.com/invertase/react-native-google-mobile-ads/blob/c0c3df6874033b98b6d7ba71643b486af394a9b4/android/build.gradle#L19-L27

Are you defining ext.kotlinVersion?  You are. So it looks like it's working or should be

Thus, needs https://stackoverflow.com/help/minimal-reproducible-example

**Comment by jihokim2** [comment]
I think this is is related to [https://github.com/invertase/react-native-google-mobile-ads/issues/476](https://github.com/invertase/react-native-google-mobile-ads/issues/476) 
Because I found log like this.
`/node_modules/react-native-google-mobile-ads/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsFullScreenAdModule.kt:148:5 'onAdLoaded' overrides nothing`
This issue occurs just in kotlin 1.9.x
Furthermore, I deleted 'onAdLoaded' function, build is successful.
I try to remove this bug, But I don't know how to fix it.
If I have more time, I will make minimal-reporducible-example.

**Comment by mikehardy** [comment]
Good find @jihokim2 - I reopened that issue as it is focused directly on a real error message right from the start, whereas your issue doesn't have that until a comment much later. Please follow along on there

Hopefully someone has a moment to see what's wrong with the override there, it is likely a pretty simple fix
