### ISSUE TITLE
Please where can i add the variable $RNGoogleMobileAdsAsStaticFramework = true ? 

### ISSUE THREAD

**Issue by Ahamet2020** [invertase/react-native-google-mobile-ads#498]
### Documentation Feedback

Please where can i add the variable $RNGoogleMobileAdsAsStaticFramework = true ?  in witch file for those who work with Expo aes

**Comment by Ahamet2020** [comment]
![Screenshot from 2023-12-08 13-04-02](https://github.com/invertase/react-native-google-mobile-ads/assets/133663243/90043bf5-0f0a-4948-9376-77cc2af69117)
i have just installed it and the app crashed

**Comment by mikehardy** [comment]
Expo support is community provided, and unless you post an Expo config plugin PR (please feel free to, if you need one to add the variable mentioned or if there is some documentation missing on how to just add a variable to a Podfile using existing Expo config plugins) it is not something the maintainers here will pursue - so it is not an issue we will track

Separately, this issue is missing sufficient information to help https://stackoverflow.com/help/how-to-ask
