### ISSUE TITLE
[🐛] Android: Improve ad object initialization

### ISSUE THREAD

**Issue by birdofpreyru** [invertase/react-native-google-mobile-ads#506]
### What happened?

Below (and, if applicable, in other similar places in the Android code, where ad objects are created):
https://github.com/invertase/react-native-google-mobile-ads/blob/c0c3df6874033b98b6d7ba71643b486af394a9b4/android/src/main/java/io/invertase/googlemobileads/ReactNativeGoogleMobileAdsBannerAdViewManager.java#L182

An `Activity` instance rather than `Context` should be passed into the `AdView` constructor, as per [_AdMob Mediation_ instructions](https://developers.google.com/admob/android/mediation)
![image](https://github.com/invertase/react-native-google-mobile-ads/assets/20144632/549d68fc-d3b6-45b8-99d5-10905bf8b226)

P.S.: I guess, I can make a PR later. Though looking at the existing code just above, where it checks whether `currentActivity` might be `null`, but does not check for the context to be `null`, I'd like to check with @dylancom first, if he knows whether it is possible that the current activity is indeed null at that point? If yes, what would be better, to return `null` if it is `null`, or just init with context instead, as a fallback?

### Platforms

Only on Android

### React Native Info

```Shell
N/A
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
N/A
```

### app.json

```JSON
N/A
```

**Comment by mikehardy** [comment]
All I know about "Activity" in react-native is that it *can* be null, you can never be sure that the Activity wasn't destroyed even though your code is still executing because of the async nature of the native/javascript bridge (which is Application-scoped if I understand correctly - while the Activity can come and go)

So this is kind of a fundamental mismatch between what mediation needs and how react-native works. I'm not sure how to harmonize them, all I know for certain is that your Activity can become invalid / null when you least expect it and that needs to be handled

**Comment by birdofpreyru** [comment]
Thanks @github-actions , but let's keep it open for now.

**Comment by birdofpreyru** [comment]
not stale
