### ISSUE TITLE
[📚] Need localization for iOS ATT authorization permission request

### ISSUE THREAD

**Issue by juuc** [invertase/react-native-google-mobile-ads#645]
### Documentation Feedback

Hi. Thanks for great library. For now, we should set the value of key 'NSUserTrackingUsageDescription' like below

```
// <project-root>/app.json
{
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx",
    "ios_app_id": "ca-app-pub-xxxxxxxx~xxxxxxxx",
    "user_tracking_usage_description": "This identifier will be used to deliver personalized ads to you."
  }
}
// from https://docs.page/invertase/react-native-google-mobile-ads#app-tracking-transparency-ios
```

I want to localize the description with Info.Plist by myself, but it seems not supported now when I distribute my app even if I set correctly in my Info.plist (not app.json). Is there any room to do this?

**Comment by mikehardy** [comment]
Interesting - do you mean you have a structure that looks sort of like:

```
app/ios/<name>/
   Info.plist
   en.lproj/InfoPlist.strings
   es.lproj/InfoPlist.strings
```

and in the Info.plist you have a placeholder for the key so that the different language codes should get their localized strings? That's how I've done it with other strings

I see in this library that we only put the value into Info.plist if you provide it - it is conditional and ignored if empty:

https://github.com/invertase/react-native-google-mobile-ads/blob/906c58a3ba61e185d7df8b04cc464ab299a309ac/ios_config.sh#L139-L145

Have you attempted to just leave that key empty in the json config? At that point the underlying / native iOS string localization should work for you in the same way as any other strings - but you have to do it at the native layer
